FROM python:3.12

WORKDIR /code

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN python -m nltk.downloader punkt # this is only needed if summarizer is based on textrank

COPY app app
COPY main.py .
COPY data data

CMD ["streamlit", "run", "main.py"]