FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY app app
COPY main.py .
COPY data data

CMD ["streamlit", "run", "main.py"]